server:
  port: 8078
  
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}  
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ProfileDB
      repositories:
        enabled: true  

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    hostname: localhost
